/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_publicinterfaceworkerjs_free: (a: number, b: number) => void;
export const publicinterfaceworkerjs_addAccount: (a: number, b: number, c: number, d: number, e: number) => any;
export const publicinterfaceworkerjs_initiateTransaction: (a: number, b: number, c: number, d: number, e: number, f: bigint, g: bigint, h: any, i: number, j: number, k: any, l: any) => any;
export const publicinterfaceworkerjs_senderConfirm: (a: number, b: any) => any;
export const publicinterfaceworkerjs_watchTxUpdates: (a: number, b: any) => any;
export const publicinterfaceworkerjs_unsubscribeWatchTxUpdates: (a: number) => void;
export const publicinterfaceworkerjs_watchP2pNotifications: (a: number, b: any) => any;
export const publicinterfaceworkerjs_unsubscribeWatchP2pNotifications: (a: number) => void;
export const publicinterfaceworkerjs_fetchPendingTxUpdates: (a: number) => any;
export const publicinterfaceworkerjs_receiverConfirm: (a: number, b: any) => any;
export const publicinterfaceworkerjs_revertTransaction: (a: number, b: any, c: number, d: number) => any;
export const publicinterfaceworkerjs_exportStorage: (a: number) => any;
export const publicinterfaceworkerjs_getNodeConnectionStatus: (a: number) => [number, number, number];
export const publicinterfaceworkerjs_clearRevertedFromCache: (a: number) => void;
export const publicinterfaceworkerjs_clearFinalizedFromCache: (a: number) => void;
export const start_vane_web3: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: any) => any;
export const __wbg_requestarguments_free: (a: number, b: number) => void;
export const requestarguments_method: (a: number) => [number, number];
export const requestarguments_params: (a: number) => any;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_6: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hff5c85c2ca770dbc: (a: number, b: number) => void;
export const closure1194_externref_shim: (a: number, b: number, c: any) => void;
export const closure1552_externref_shim: (a: number, b: number, c: any) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h7876d40aeac1bca2: (a: number, b: number) => void;
export const closure1950_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
